# Generated by Django 5.1.5 on 2025-02-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_detail',
            field=models.CharField(max_length=300),
        ),
    ]
